name: urban_mobility
version: "1.0.0"
config-version: 2

profile: urban_mobility

model-paths: ["models"]

models:
  urban_mobility:
    staging:
      +materialized: view
    marts:
      +materialized: table
